project:
  type: website

website:
  title: "qaurto-blog-email-notifications"
  site-url: https://colorado.posit.co/rsc/content/1561d39e-977a-4e5c-9e73-857860b3d076/
  description: "A great sample blog"  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

